<?php

return [

    'site_name' => 'Faizan Rehabilitation Center',
    'site_url' => env('APP_URL', 'https://www.faizanrehab.org'),
    'locale' => 'en_PK',
    'twitter_handle' => '',

    'organization' => [
        'name' => 'Faizan Rehabilitation Center',
        'alternate_name' => 'FRC',
        'url' => env('APP_URL', 'https://www.faizanrehab.org'),
        'logo' => '/images/logo.png',
        'email' => 'info@faizanrehab.org',
        'telephone' => '+92-21-111113473',
        'address' => [
            'street' => "Ground Floor, Ceasar's Tower, Shahrah-e-Faisal",
            'city' => 'Karachi',
            'region' => 'Sindh',
            'country' => 'PK',
        ],
        'geo' => [
            'latitude' => '24.8607',
            'longitude' => '67.0011',
        ],
        'opening_hours' => 'Mo-Sa 09:00-18:00',
        'facebook' => 'https://www.facebook.com/faizanrehabcenter',
    ],

    'defaults' => [
        'title' => 'Faizan Rehabilitation Center',
        'description' => 'Faizan Rehabilitation Center (FRC) offers expert physiotherapy, speech therapy, occupational therapy and behavioral therapy for children with special needs in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
        'keywords' => 'rehabilitation center karachi, special needs therapy, child therapy pakistan, faizan rehabilitation center, rehabilitation center lahore, rehabilitation center faisalabad, rehabilitation center sialkot, rehabilitation center pakistan',
        'og_image' => '/images/main-slider.jpg',
        'robots' => 'index, follow',
    ],

    'pages' => [
        'index' => [
            'title' => 'Faizan Rehabilitation Center',
            'description' => 'Faizan Rehabilitation Center (FRC) empowers children with special needs through physiotherapy, speech therapy, occupational therapy and behavioral therapy in Karachi, Lahore and Faisalabad, Sialkot, Pakistan. Book an appointment today.',
            'keywords' => 'rehabilitation center karachi, special needs children therapy, child development center pakistan, faizan rehab, autism therapy karachi, rehabilitation center lahore, rehabilitation center faisalabad, rehabilitation center sialkot, rehabilitation center pakistan',
            'og_image' => '/images/main-slider.jpg',
            'changefreq' => 'weekly',
            'priority' => '1.0',
        ],
        'about-us' => [
            'title' => 'About Us | Faizan Rehabilitation Center',
            'description' => 'Learn about Faizan Rehabilitation Center — our mission, vision, core values and commitment to providing compassionate, professional therapy for children with special needs in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'about faizan rehabilitation center, special needs rehab karachi, child therapy center pakistan, FRC mission vision',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'services' => [
            'title' => 'Our Services | Faizan Rehabilitation Center',
            'description' => 'Explore comprehensive therapy services at Faizan Rehabilitation Center including speech therapy, physiotherapy, occupational therapy, behavioral therapy and more for children in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'rehabilitation services karachi, child therapy services, special education pakistan, therapy programs for children, rehabilitation services lahore, rehabilitation services faisalabad, rehabilitation services sialkot, rehabilitation services pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.9',
        ],
        'remedial-therapy' => [
            'title' => 'Remedial Therapy for Children | Faizan Rehabilitation Center',
            'description' => 'Expert remedial therapy at Faizan Rehabilitation Center helps children overcome learning difficulties with personalized educational support and evidence-based interventions in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'remedial therapy karachi, learning difficulties therapy, special education karachi, remedial education children, remediation therapy lahore, remediation therapy faisalabad, remediation therapy sialkot, remediation therapy pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'speech-therapy' => [
            'title' => 'Speech Therapy for Children | Faizan Rehabilitation Center Karachi',
            'description' => 'Professional speech therapy at Faizan Rehabilitation Center treats speech delays, articulation disorders and communication challenges in children. Expert therapists in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'speech therapy karachi, speech therapist for children, language delay treatment, communication therapy pakistan, speech therapy lahore, speech therapy faisalabad, speech therapy sialkot, speech therapy pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'occupational-therapy' => [
            'title' => 'Occupational Therapy for Children | Faizan Rehabilitation Center',
            'description' => 'Occupational therapy at Faizan Rehabilitation Center improves fine motor skills, sensory processing and daily living skills for children with special needs in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'occupational therapy karachi, pediatric OT, sensory integration therapy, fine motor skills children, occupational therapy lahore, occupational therapy faisalabad, occupational therapy sialkot, occupational therapy pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'physiotherapy' => [
            'title' => 'Pediatric Physiotherapy | Faizan Rehabilitation Center',
            'description' => 'Pediatric physiotherapy at Faizan Rehabilitation Center helps children improve mobility, strength and motor development through expert, child-friendly treatment in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'pediatric physiotherapy karachi, child physiotherapist, motor development therapy, physical therapy children pakistan, physiotherapy lahore, physiotherapy faisalabad, physiotherapy sialkot, physiotherapy pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'behavioral-therapy' => [
            'title' => 'Behavioral Therapy for Children | Faizan Rehabilitation Center',
            'description' => 'Behavioral therapy at Faizan Rehabilitation Center supports children with autism, ADHD and behavioral challenges using evidence-based ABA and positive behavior strategies in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'behavioral therapy karachi, ABA therapy children, autism behavior therapy, ADHD treatment karachi, behavioral therapy lahore, behavioral therapy faisalabad, behavioral therapy sialkot, behavioral therapy pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'school-readiness-program' => [
            'title' => 'School Readiness Program | Faizan Rehabilitation Center',
            'description' => 'Prepare your child for school success with Faizan Rehabilitation Center\'s School Readiness Program — building academic, social and emotional skills for children in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'school readiness program karachi, pre-school preparation, special needs school readiness, early childhood education pakistan, school readiness program lahore, school readiness program faisalabad, school readiness program sialkot, school readiness program pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.7',
        ],
        'quran-teaching' => [
            'title' => 'Quran Teaching for Special Needs Children | Faizan Rehabilitation Center',
            'description' => 'Specialized Quran teaching program at Faizan Rehabilitation Center helps children with special needs learn Quran recitation with patience, care and individualized teaching methods in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'quran teaching special needs, islamic education children karachi, quran classes special children pakistan, quran teaching lahore, quran teaching faisalabad, quran teaching sialkot, quran teaching pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.7',
        ],
        'parental-counselling' => [
            'title' => 'Parental Counselling | Faizan Rehabilitation Center',
            'description' => 'Parental counselling at Faizan Rehabilitation Center guides families of children with special needs through emotional support, coping strategies and home-based intervention plans.',
            'keywords' => 'parental counselling karachi, special needs parent support, family counselling children disability, parent guidance therapy, parental counselling lahore, parental counselling faisalabad, parental counselling sialkot, parental counselling pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.7',
        ],
        'group-therapy' => [
            'title' => 'Group Therapy for Children | Faizan Rehabilitation Center',
            'description' => 'Group therapy sessions at Faizan Rehabilitation Center help children develop social skills, peer interaction and emotional growth in a supportive, structured environment in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'group therapy children karachi, social skills therapy, peer interaction special needs, group sessions rehabilitation, group therapy lahore, group therapy faisalabad, group therapy sialkot, group therapy pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.7',
        ],
        'our-therapists' => [
            'title' => 'Our Therapists | Faizan Rehabilitation Center',
            'description' => 'Meet the qualified, experienced therapists at Faizan Rehabilitation Center — dedicated professionals providing speech, occupational, physical and behavioral therapy for children.',
            'keywords' => 'rehabilitation therapists karachi, speech therapist karachi, occupational therapist pakistan, child therapy specialists, rehabilitation therapists lahore, rehabilitation therapists faisalabad, rehabilitation therapists sialkot, rehabilitation therapists pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.7',
        ],
        'gallery' => [
            'title' => 'Gallery | Faizan Rehabilitation Center',
            'description' => 'View photos from Faizan Rehabilitation Center — our facilities, therapy sessions, events and the children we proudly serve across Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'faizan rehab gallery, rehabilitation center photos, therapy center karachi images, rehabilitation center photos lahore, rehabilitation center photos faisalabad, rehabilitation center photos sialkot, rehabilitation center photos pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.5',
        ],
        'contact-us' => [
            'title' => 'Contact Us | Faizan Rehabilitation Center',
            'description' => 'Contact Faizan Rehabilitation Center in Karachi. Call 021-111-11-3473 or email info@faizanrehab.org. Branches in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'contact faizan rehabilitation center, rehab center karachi address, FRC phone number, therapy center contact pakistan, rehab center lahore address, rehab center faisalabad address, rehab center sialkot address, rehab center pakistan address',
            'changefreq' => 'monthly',
            'priority' => '0.8',
        ],
        'appointment' => [
            'title' => 'Book Appointment | Faizan Rehabilitation Center',
            'description' => 'Book an appointment at Faizan Rehabilitation Center for your child\'s therapy assessment. Easy online booking for speech, physiotherapy, occupational and behavioral therapy in Karachi, Lahore and Faisalabad, Sialkot, Pakistan.',
            'keywords' => 'book appointment rehab center karachi, therapy appointment children, FRC appointment booking, child therapy consultation, book appointment rehab center lahore, book appointment rehab center faisalabad, book appointment rehab center sialkot, book appointment rehab center pakistan',
            'changefreq' => 'monthly',
            'priority' => '0.9',
        ],
    ],

    'sitemap' => [
        'index',
        'about-us',
        'services',
        'remedial-therapy',
        'speech-therapy',
        'occupational-therapy',
        'physiotherapy',
        'behavioral-therapy',
        'school-readiness-program',
        'quran-teaching',
        'parental-counselling',
        'group-therapy',
        'our-therapists',
        'gallery',
        'contact-us',
        'appointment',
    ],

];
